# Generated by Django 6.0.6 on 2026-06-04 09:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_role_and_transactions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('pet', models.CharField(choices=[('Cat', ' Cat'), ('Dog', ' Dog')], default='Cat', max_length=10, verbose_name='Pet Type')),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Vitamins', 'Vitamins'), ('Grooming', 'Grooming'), ('Toys', 'Toys'), ('Accessories', 'Accessories')], max_length=50, verbose_name='Category')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (Rp)')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Quantity')),
                ('date_added', models.DateField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='barangmasuk',
            name='barang',
        ),
        migrations.RemoveField(
            model_name='barangkeluar',
            name='barang',
        ),
        migrations.RemoveField(
            model_name='historitransaksi',
            name='barang',
        ),
        migrations.RemoveField(
            model_name='barangkeluar',
            name='dicatat_oleh',
        ),
        migrations.RemoveField(
            model_name='barangmasuk',
            name='dicatat_oleh',
        ),
        migrations.RemoveField(
            model_name='historitransaksi',
            name='dicatat_oleh',
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('user_role', models.CharField(blank=True, max_length=20)),
                ('activity_type', models.CharField(choices=[('PRODUCT_ADDED', ' Product Added'), ('PRODUCT_UPDATED', ' Product Updated'), ('PRODUCT_DELETED', ' Product Deleted'), ('LOGIN', ' Login'), ('LOGOUT', ' Logout')], max_length=20)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity In')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_in_records', to='inventory.product')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity Out')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_out_records', to='inventory.product')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', ' Stock In'), ('OUT', ' Stock Out')], max_length=3)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_history', to='inventory.product')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', ' Owner'), ('admin', ' Admin'), ('staff', ' Staff')], default='staff', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Barang',
        ),
        migrations.DeleteModel(
            name='BarangKeluar',
        ),
        migrations.DeleteModel(
            name='BarangMasuk',
        ),
        migrations.DeleteModel(
            name='HistoriTransaksi',
        ),
    ]
