# Generated by Django 4.2.30 on 2026-06-23 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_remove_barangmasuk_barang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('PRODUCT_ADDED', 'Product Added'), ('PRODUCT_UPDATED', 'Product Updated'), ('PRODUCT_DELETED', 'Product Deleted'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT_CSV', 'Export CSV'), ('EXPORT_XLSX', 'Export Excel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='pet',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], default='Cat', max_length=10, verbose_name='Pet Type'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_in_records', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_out_records', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_history', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('stock__gte', 0)), name='stock_cannot_be_negative'),
        ),
    ]
